// -------------------------------------------------------------
// 
// File Name: hdl_prj_pattern3/hdlsrc/pattern_hdlcoder_led_blinking/led_count_ip.v
// Created: 2023-10-26 13:10:23
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: led_count_ip
// Source Path: led_count_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module led_count_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           CFARI0,
           CFARI1,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           THo_0,
           THo_1,
           THo_2,
           PDWO,
           logouto,
           Inchanno,
           thcwo,
           th2cwo,
           th1cwo,
           pattern,
           P_to_Bo,
           pdivo,
           P_to_So,
           DACseleso,
           CHselo,
           GPIO_LED,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   [15:0] CFARI0;  // ufix16
  input   [15:0] CFARI1;  // ufix16
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  [15:0] THo_0;  // ufix16
  output  [15:0] THo_1;  // ufix16
  output  [15:0] THo_2;  // ufix16
  output  PDWO;  // ufix1
  output  [15:0] logouto;  // ufix16
  output  [31:0] Inchanno;  // ufix32
  output  [31:0] thcwo;  // ufix32
  output  [15:0] th2cwo;  // ufix16
  output  [15:0] th1cwo;  // ufix16
  output  [63:0] pattern;  // ufix16
  output  [15:0] P_to_Bo;  // ufix16
  output  [15:0] pdivo;  // ufix16
  output  [15:0] P_to_So;  // ufix16
  output  [1:0] DACseleso;  // ufix16
  output  [15:0] CHselo;  // ufix16
  output  [7:0] GPIO_LED;  // ufix8
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire [15:0] CFAR0_sig;  // ufix16
  wire [15:0] CFAR1_sig;  // ufix16
  wire [15:0] Teta_Azo_sig;  // ufix16
  wire [15:0] Num_Sideo_sig;  // ufix16
  wire [15:0] Num_Backo_sig;  // ufix16
  wire write_axi_enable;  // ufix1
  wire [15:0] write_TH0;  // ufix16
  wire write_En_PATTERN;  // ufix1
  wire [15:0] write_TH1;  // ufix16
  wire [15:0] write_TH2;  // ufix16
  wire write_PDW;  // ufix1
  wire [15:0] write_logouti;  // ufix16
  wire [31:0] write_INchann;  // ufix32
  wire [31:0] write_thcw;  // ufix32
  wire [15:0] write_th1cw;  // ufix16
  wire [15:0] write_th2cw;  // ufix16
  wire [31:0] write_NPS;  // ufix32
  wire [15:0] write_P_to_B;  // ufix16
  wire [15:0] write_P_to_S;  // ufix16
  wire [15:0] write_pdiv;  // ufix16
  wire [15:0] write_DACseles;  // ufix16
  wire [15:0] write_CHsel;  // ufix16
  wire [15:0] write_Teta_Az;  // ufix16
  wire [15:0] write_Num_Side;  // ufix16
  wire [15:0] write_Num_Back;  // ufix16
  wire ce_out_sig;  // ufix1
  wire [7:0] LED_sig;  // ufix8
  wire [15:0] THo_0_sig;  // ufix16
  wire [15:0] THo_1_sig;  // ufix16
  wire [15:0] THo_2_sig;  // ufix16
  wire PDWO_sig;  // ufix1
  wire [15:0] logouto_sig;  // ufix16
  wire [31:0] Inchanno_sig;  // ufix32
  wire [31:0] thcwo_sig;  // ufix32
  wire [15:0] th2cwo_sig;  // ufix16
  wire [15:0] th1cwo_sig;  // ufix16
  wire [63:0] pattern_sig;  // ufix16
  wire [15:0] P_to_Bo_sig;  // ufix16
  wire [15:0] pdivo_sig;  // ufix16
  wire [15:0] P_to_So_sig;  // ufix16
  wire [1:0] DACseleso_sig;  // ufix16
  wire [15:0] CHselo_sig;  // ufix16


  assign ip_timestamp = 32'b10001001101100111100101000111110;



  assign reset_cm =  ~ IPCORE_RESETN;



  assign reset_before_sync = reset_cm | reset_internal;



  led_count_ip_reset_sync u_led_count_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                          .reset_in(reset_before_sync),  // ufix1
                                                          .reset_out(reset)
                                                          );

  led_count_ip_axi_lite u_led_count_ip_axi_lite_inst (.reset(reset),
                                                      .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                                      .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                      .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                      .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                      .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                      .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                      .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                      .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                      .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                      .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                      .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                      .read_ip_timestamp(ip_timestamp),  // ufix32
                                                      .read_CFAR0(CFAR0_sig),  // ufix16
                                                      .read_CFAR1(CFAR1_sig),  // ufix16
                                                      .read_Teta_Azo(Teta_Azo_sig),  // ufix16
                                                      .read_Num_Sideo(Num_Sideo_sig),  // ufix16
                                                      .read_Num_Backo(Num_Backo_sig),  // ufix16
                                                      .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                      .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                      .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                      .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                      .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                      .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                      .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                      .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                      .write_axi_enable(write_axi_enable),  // ufix1
                                                      .write_TH0(write_TH0),  // ufix16
                                                      .write_En_PATTERN(write_En_PATTERN),  // ufix1
                                                      .write_TH1(write_TH1),  // ufix16
                                                      .write_TH2(write_TH2),  // ufix16
                                                      .write_PDW(write_PDW),  // ufix1
                                                      .write_logouti(write_logouti),  // ufix16
                                                      .write_INchann(write_INchann),  // ufix32
                                                      .write_thcw(write_thcw),  // ufix32
                                                      .write_th1cw(write_th1cw),  // ufix16
                                                      .write_th2cw(write_th2cw),  // ufix16
                                                      .write_NPS(write_NPS),  // ufix32
                                                      .write_P_to_B(write_P_to_B),  // ufix16
                                                      .write_P_to_S(write_P_to_S),  // ufix16
                                                      .write_pdiv(write_pdiv),  // ufix16
                                                      .write_DACseles(write_DACseles),  // ufix16
                                                      .write_CHsel(write_CHsel),  // ufix16
                                                      .write_Teta_Az(write_Teta_Az),  // ufix16
                                                      .write_Num_Side(write_Num_Side),  // ufix16
                                                      .write_Num_Back(write_Num_Back),  // ufix16
                                                      .reset_internal(reset_internal)  // ufix1
                                                      );

  led_count_ip_dut u_led_count_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                            .reset(reset),
                                            .dut_enable(write_axi_enable),  // ufix1
                                            .TH0(write_TH0),  // ufix16
                                            .En_PATTERN(write_En_PATTERN),  // ufix1
                                            .TH1(write_TH1),  // ufix16
                                            .TH2(write_TH2),  // ufix16
                                            .PDW(write_PDW),  // ufix1
                                            .CFARI0(CFARI0),  // ufix16
                                            .CFARI1(CFARI1),  // ufix16
                                            .logouti(write_logouti),  // ufix16
                                            .INchann(write_INchann),  // ufix32
                                            .thcw(write_thcw),  // ufix32
                                            .th1cw(write_th1cw),  // ufix16
                                            .th2cw(write_th2cw),  // ufix16
                                            .NPS(write_NPS),  // ufix32
                                            .P_to_B(write_P_to_B),  // ufix16
                                            .P_to_S(write_P_to_S),  // ufix16
                                            .pdiv(write_pdiv),  // ufix16
                                            .DACseles(write_DACseles),  // ufix16
                                            .CHsel(write_CHsel),  // ufix16
                                            .Teta_Az(write_Teta_Az),  // ufix16
                                            .Num_Side(write_Num_Side),  // ufix16
                                            .Num_Back(write_Num_Back),  // ufix16
                                            .ce_out(ce_out_sig),  // ufix1
                                            .LED(LED_sig),  // ufix8
                                            .CFAR0(CFAR0_sig),  // ufix16
                                            .THo_0(THo_0_sig),  // ufix16
                                            .THo_1(THo_1_sig),  // ufix16
                                            .THo_2(THo_2_sig),  // ufix16
                                            .CFAR1(CFAR1_sig),  // ufix16
                                            .PDWO(PDWO_sig),  // ufix1
                                            .logouto(logouto_sig),  // ufix16
                                            .Inchanno(Inchanno_sig),  // ufix32
                                            .thcwo(thcwo_sig),  // ufix32
                                            .th2cwo(th2cwo_sig),  // ufix16
                                            .th1cwo(th1cwo_sig),  // ufix16
                                            .pattern(pattern_sig),  // ufix16
                                            .P_to_Bo(P_to_Bo_sig),  // ufix16
                                            .pdivo(pdivo_sig),  // ufix16
                                            .P_to_So(P_to_So_sig),  // ufix16
                                            .DACseleso(DACseleso_sig),  // ufix16
                                            .CHselo(CHselo_sig),  // ufix16
                                            .Teta_Azo(Teta_Azo_sig),  // ufix16
                                            .Num_Sideo(Num_Sideo_sig),  // ufix16
                                            .Num_Backo(Num_Backo_sig)  // ufix16
                                            );

  assign THo_0 = THo_0_sig;

  assign THo_1 = THo_1_sig;

  assign THo_2 = THo_2_sig;

  assign PDWO = PDWO_sig;

  assign logouto = logouto_sig;

  assign Inchanno = Inchanno_sig;

  assign thcwo = thcwo_sig;

  assign th2cwo = th2cwo_sig;

  assign th1cwo = th1cwo_sig;

  assign pattern = pattern_sig;

  assign P_to_Bo = P_to_Bo_sig;

  assign pdivo = pdivo_sig;

  assign P_to_So = P_to_So_sig;

  assign DACseleso = DACseleso_sig;

  assign CHselo = CHselo_sig;

  assign GPIO_LED = LED_sig;

endmodule  // led_count_ip

